#!/bin/sh

set -x
set -e

ARCH="x86_64"
OS="macos"
ARCH_OS="${ARCH}-${OS}"
OS_ARCH="${OS}-${ARCH}"

ZIG_SRC="https://ziglang.org/download/index.json"
ZIG_VERSION=$(curl -s ${ZIG_SRC} | jq -r '.master.version')
ZIG="zig-${OS_ARCH}-$ZIG_VERSION"
ZIG_MASTER=$(curl -s ${ZIG_SRC} | jq -r --arg ARCH_OS "$ARCH_OS" '.master[$ARCH_OS].tarball')

WASMTIME_VERSION="v0.37.0"
WASMTIME="wasmtime-$WASMTIME_VERSION-x86_64-macos-c-api"
GYRO_VERSION="0.7.0"
GYRO="gyro-$GYRO_VERSION-macos-x86_64"

curl -sL "${ZIG_MASTER}" -o "$ZIG.tar.xz"
tar xf "$ZIG.tar.xz"
export PATH="$(pwd)/$ZIG:$PATH"

./ci/install_wasmtime $WASMTIME_VERSION $WASMTIME

./ci/install_gyro $GYRO_VERSION $GYRO
export PATH="$(pwd)/$GYRO/bin:$PATH"

./ci/run_gyro $WASMTIME
