#!/bin/sh

set -x
set -e

ARCH="x86_64"
OS="windows"
ARCH_OS="${ARCH}-${OS}"
OS_ARCH="${OS}-${ARCH}"

ZIG_SRC="https://ziglang.org/download/index.json"
ZIG_VERSION=$(curl -s ${ZIG_SRC} | jq -r '.master.version')
ZIG="zig-${OS_ARCH}-$ZIG_VERSION"
ZIG_MASTER=$(curl -s ${ZIG_SRC} | jq -r --arg ARCH_OS "$ARCH_OS" '.master[$ARCH_OS].tarball')

WASMTIME_VERSION="v0.37.0"
WASMTIME="wasmtime-$WASMTIME_VERSION-${ARCH_OS}-c-api"
GYRO_VERSION="0.7.0"
GYRO="gyro-$GYRO_VERSION-${OS_ARCH}"

curl -sL "${ZIG_MASTER}" -o "$ZIG.zip"
7z x "$ZIG.zip"
export PATH="$(pwd)/$ZIG:$PATH"

curl -sL "https://github.com/bytecodealliance/wasmtime/releases/download/$WASMTIME_VERSION/$WASMTIME.zip" -o "$WASMTIME.zip"
7z x "$WASMTIME.zip"

curl -sL "https://github.com/mattnite/gyro/releases/download/$GYRO_VERSION/$GYRO.zip" -o "$GYRO.zip"
7z x "$GYRO.zip"
export PATH="$(pwd)/$GYRO/bin:$PATH"

./ci/run_gyro $WASMTIME
