name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # run at 00:00 UTC

jobs:
  build_nix:
    name: Build and test
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macos, ubuntu, windows]

    steps:
    - name: Configure git
      if: matrix.os == 'windows'
      run: |
        git config --global core.autocrlf false
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test linux
      if: matrix.os == 'ubuntu'
      run: ./ci/linux_ci
    - name: Test macos
      if: matrix.os == 'macos'
      run: ./ci/macos_ci
    - name: Test windows
      shell: bash
      if: matrix.os == 'windows'
      run: ./ci/win_ci
